In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('superstore_messy_dataset.csv')

In [5]:
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,ORD-1,2021-04-13,2023-08-14,Standard Class,CUST-5510,Rahul,Corporate,India,Delhi,WB,North,PROD-420,Office Supplies,Chairs,Item A,1084.46,6,NaN,-18.78
1,ORD-2,2022-03-12,2021-10-08,Standard Class,CUST-1393,Rahul,Corporate,India,Mumbai,WB,East,PROD-441,Technology,Binders,Item C,4576.87,2,0.46,-1274.67
2,ORD-3,2023-05-11,2021-09-10,Standard Class,CUST-9005,Amit,Consumer,India,Bangalore,MH,South,PROD-127,Office Supplies,Storage,Item C,764.96,8,0.31,-74.58
3,ORD-4,2021-09-28,2021-11-08,First Class,CUST-4686,Arjun,Consumer,India,Kolkata,DL,North,PROD-413,Office Supplies,Phones,Item D,1522.06,4,0.02,134.90
4,ORD-5,2021-04-17,2022-12-23,First Class,CUST-1357,Sneha,Home Office,India,Kolkata,DL,East,PROD-314,Furniture,Chairs,Item B,1060.52,6,0.41,-276.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10195,ORD-8954,2022-10-27,2021-12-01,First Class,CUST-3508,Amit,Corporate,India,Bangalore,KA,South,PROD-516,Technology,Storage,Item C,2060.48,2,0.13,116.45
10196,ORD-4922,2022-01-05,2022-05-06,Second Class,CUST-7345,Amit,Consumer,India,Bangalore,WB,North,PROD-346,Office Supplies,Storage,Item B,4678.69,4,0.36,-800.04
10197,ORD-5512,2022-09-05,2021-03-10,First Class,CUST-9151,Sneha,Home Office,India,Kolkata,DL,South,PROD-653,Technology,Storage,Item A,2493.12,5,0.21,-40.60
10198,ORD-2620,2021-01-24,2021-04-30,First Class,CUST-9805,Sneha,Corporate,India,Mumbai,DL,North,PROD-723,Furniture,Phones,Item B,2147.98,4,0.17,5.86
10199,ORD-1114,2021-12-01,2023-09-29,Standard Class,CUST-9572,Neha,Corporate,India,Delhi,WB,North,PROD-218,Furniture,Binders,Item B,4074.46,8,0.41,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       10200 non-null  object
 1   Order Date     10200 non-null  object
 2   Ship Date      10200 non-null  object
 3   Ship Mode      10200 non-null  object
 4   Customer ID    10200 non-null  object
 5   Customer Name  10200 non-null  object
 6   Segment        10200 non-null  object
 7   Country        10200 non-null  object
 8   City           9687 non-null   object
 9   State          10200 non-null  object
 10  Region         10200 non-null  object
 11  Product ID     10200 non-null  object
 12  Category       10200 non-null  object
 13  Sub-Category   10200 non-null  object
 14  Product Name   10200 non-null  object
 15  Sales          9690 non-null   float64
 16  Quantity       10200 non-null  int64
 17  Discount       9691 non-null   float64
 18  Profit         9686 non-null   float64
dtypes: float64(3), int64(1), object(15)
memory usage: 1.5+ MB

In [7]:
df.duplicated().any()

np.True_

In [8]:
df.describe()

             Sales      Quantity     Discount       Profit
count  9690.000000  10200.000000  9691.000000  9686.000000
mean   2545.628851      4.966961     0.251417  -130.549307
std    1431.455178      2.571687     0.144310   429.654109
min      50.890000      1.000000     0.000000 -1519.240000
25%    1291.402500      3.000000     0.120000  -377.815000
50%    2570.385000      5.000000     0.250000   -75.060000
75%    3805.920000      7.000000     0.370000   122.482500
max    4999.340000      9.000000     0.500000  1068.880000

In [9]:
df.isnull().sum()

Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country            0
City             513
State              0
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales            510
Quantity           0
Discount         509
Profit           514
dtype: int64

In [10]:
#remove all duplicates value

df.drop_duplicates(inplace=True)

In [11]:
df['City'].fillna(df['City'].mode()[0],inplace=True)

/tmp/ipykernel_7204/1611917902.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['City'].fillna(df['City'].mode()[0],inplace=True)

In [12]:
df['Sales'].fillna(df['Sales'].median(),inplace=True)

/tmp/ipykernel_7204/2121960062.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sales'].fillna(df['Sales'].median(),inplace=True)

In [ ]:
df['Discount'].fillna(df['Discount'].median(),inplace=True)

/tmp/ipykernel_6963/1192084963.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Discount'].fillna(df['Discount'].median(),inplace=True)

In [13]:
df['Profit'].fillna(df['Profit'].median(),inplace=True)

/tmp/ipykernel_7204/2645793250.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Profit'].fillna(df['Profit'].median(),inplace=True)

In [14]:
df.isnull().sum()

Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country            0
City               0
State              0
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Quantity           0
Discount         500
Profit             0
dtype: int64

In [15]:
df['City'].unique()

array(['Delhi', 'Mumbai', 'Bangalore', 'Kolkata'], dtype=object)

In [16]:
df['City']=df['Discount']*df['Profit']

In [ ]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,ORD-1,2021-04-13,2023-08-14,Standard Class,CUST-5510,Rahul,Corporate,India,-4.711322,WB,North,PROD-420,Office Supplies,Chairs,Item A,1084.46,6,0.250869,-18.78
1,ORD-2,2022-03-12,2021-10-08,Standard Class,CUST-1393,Rahul,Corporate,India,-586.348200,WB,East,PROD-441,Technology,Binders,Item C,4576.87,2,0.460000,-1274.67
2,ORD-3,2023-05-11,2021-09-10,Standard Class,CUST-9005,Amit,Consumer,India,-23.119800,MH,South,PROD-127,Office Supplies,Storage,Item C,764.96,8,0.310000,-74.58
3,ORD-4,2021-09-28,2021-11-08,First Class,CUST-4686,Arjun,Consumer,India,2.698000,DL,North,PROD-413,Office Supplies,Phones,Item D,1522.06,4,0.020000,134.90
4,ORD-5,2021-04-17,2022-12-23,First Class,CUST-1357,Sneha,Home Office,India,-113.512600,DL,East,PROD-314,Furniture,Chairs,Item B,1060.52,6,0.410000,-276.86

In [17]:
#converts dates
df['Order Date']=pd.to_datetime(df['Order Date'])

In [18]:
#converts dates
df['Ship Date']=pd.to_datetime(df['Ship Date'])

In [19]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,ORD-1,2021-04-13,2023-08-14,Standard Class,CUST-5510,Rahul,Corporate,India,NaN,WB,North,PROD-420,Office Supplies,Chairs,Item A,1084.46,6,NaN,-18.78
1,ORD-2,2022-03-12,2021-10-08,Standard Class,CUST-1393,Rahul,Corporate,India,-586.3482,WB,East,PROD-441,Technology,Binders,Item C,4576.87,2,0.46,-1274.67
2,ORD-3,2023-05-11,2021-09-10,Standard Class,CUST-9005,Amit,Consumer,India,-23.1198,MH,South,PROD-127,Office Supplies,Storage,Item C,764.96,8,0.31,-74.58
3,ORD-4,2021-09-28,2021-11-08,First Class,CUST-4686,Arjun,Consumer,India,2.6980,DL,North,PROD-413,Office Supplies,Phones,Item D,1522.06,4,0.02,134.90
4,ORD-5,2021-04-17,2022-12-23,First Class,CUST-1357,Sneha,Home Office,India,-113.5126,DL,East,PROD-314,Furniture,Chairs,Item B,1060.52,6,0.41,-276.86

In [20]:
# extract month and year
df['Order Month']=df['Order Date'].dt.month
df['Order Year']=df['Order Date'].dt.year

In [21]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Month,Order Year
0,ORD-1,2021-04-13,2023-08-14,Standard Class,CUST-5510,Rahul,Corporate,India,NaN,WB,...,PROD-420,Office Supplies,Chairs,Item A,1084.46,6,NaN,-18.78,4,2021
1,ORD-2,2022-03-12,2021-10-08,Standard Class,CUST-1393,Rahul,Corporate,India,-586.3482,WB,...,PROD-441,Technology,Binders,Item C,4576.87,2,0.46,-1274.67,3,2022
2,ORD-3,2023-05-11,2021-09-10,Standard Class,CUST-9005,Amit,Consumer,India,-23.1198,MH,...,PROD-127,Office Supplies,Storage,Item C,764.96,8,0.31,-74.58,5,2023
3,ORD-4,2021-09-28,2021-11-08,First Class,CUST-4686,Arjun,Consumer,India,2.6980,DL,...,PROD-413,Office Supplies,Phones,Item D,1522.06,4,0.02,134.90,9,2021
4,ORD-5,2021-04-17,2022-12-23,First Class,CUST-1357,Sneha,Home Office,India,-113.5126,DL,...,PROD-314,Furniture,Chairs,Item B,1060.52,6,0.41,-276.86,4,2021

In [22]:
# profit margin
df['Profit Margin']=df['Profit']/df['Sales']

In [23]:
df['Sales Category']=pd.cut(df['Sales'],
                            bins=[0,100,500,1000,5000],
                            labels=['Low','Medium','High','Very High'])

In [24]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Month,Order Year,Profit Margin,Sales Category
0,ORD-1,2021-04-13,2023-08-14,Standard Class,CUST-5510,Rahul,Corporate,India,NaN,WB,...,Chairs,Item A,1084.46,6,NaN,-18.78,4,2021,-0.017317,Very High
1,ORD-2,2022-03-12,2021-10-08,Standard Class,CUST-1393,Rahul,Corporate,India,-586.3482,WB,...,Binders,Item C,4576.87,2,0.46,-1274.67,3,2022,-0.278503,Very High
2,ORD-3,2023-05-11,2021-09-10,Standard Class,CUST-9005,Amit,Consumer,India,-23.1198,MH,...,Storage,Item C,764.96,8,0.31,-74.58,5,2023,-0.097495,High
3,ORD-4,2021-09-28,2021-11-08,First Class,CUST-4686,Arjun,Consumer,India,2.6980,DL,...,Phones,Item D,1522.06,4,0.02,134.90,9,2021,0.088630,Very High
4,ORD-5,2021-04-17,2022-12-23,First Class,CUST-1357,Sneha,Home Office,India,-113.5126,DL,...,Chairs,Item B,1060.52,6,0.41,-276.86,4,2021,-0.261061,Very High

In [25]:
#  which category is the highest  total sales

df.groupby('Category')['Sales'].sum().sort_values(ascending=False)

Category
Technology         8624383.61
Furniture          8481668.68
Office Supplies    8368070.52
Name: Sales, dtype: float64

In [26]:
# which category is the most profitable
df.groupby('Category')['Profit'].sum().sort_values(ascending=False)

Category
Technology        -391958.89
Office Supplies   -425004.36
Furniture         -447656.25
Name: Profit, dtype: float64

In [32]:
#  Are the loss making transaction
df[df['Profit']<0]

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Month,Order Year,Profit Margin,Sales Category
0,ORD-1,2021-04-13,2023-08-14,Standard Class,CUST-5510,Rahul,Corporate,India,NaN,WB,...,Chairs,Item A,1084.46,6,NaN,-18.78,4,2021,-0.017317,Very High
1,ORD-2,2022-03-12,2021-10-08,Standard Class,CUST-1393,Rahul,Corporate,India,-586.3482,WB,...,Binders,Item C,4576.87,2,0.46,-1274.67,3,2022,-0.278503,Very High
2,ORD-3,2023-05-11,2021-09-10,Standard Class,CUST-9005,Amit,Consumer,India,-23.1198,MH,...,Storage,Item C,764.96,8,0.31,-74.58,5,2023,-0.097495,High
4,ORD-5,2021-04-17,2022-12-23,First Class,CUST-1357,Sneha,Home Office,India,-113.5126,DL,...,Chairs,Item B,1060.52,6,0.41,-276.86,4,2021,-0.261061,Very High
5,ORD-6,2021-03-13,2023-04-15,Standard Class,CUST-5004,Rahul,Corporate,India,-369.8863,WB,...,Binders,Item D,2850.86,2,0.49,-754.87,3,2021,-0.264787,Very High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ORD-9996,2023-07-04,2021-04-24,First Class,CUST-2237,Priya,Corporate,India,-437.9798,MH,...,Chairs,Item A,2568.79,7,0.46,-952.13,7,2023,-0.370653,Very High
9996,ORD-9997,2021-07-29,2022-03-31,Standard Class,CUST-5943,Sneha,Home Office,India,-346.2018,KA,...,Phones,Item B,4001.25,6,0.42,-824.29,7,2021,-0.206008,Very High
9997,ORD-9998,2023-01-11,2023-01-28,First Class,CUST-5765,Arjun,Corporate,India,-0.3108,DL,...,Storage,Item D,211.57,4,0.37,-0.84,1,2023,-0.003970,Medium
9998,ORD-9999,2023-05-12,2021-06-20,First Class,CUST-5836,Amit,Corporate,India,-61.2880,KA,...,Phones,Item B,792.17,1,0.40,-153.22,5,2023,-0.193418,High
9999,ORD-10000,2021-10-02,2022-08-09,Standard Class,CUST-1459,Sneha,Corporate,India,-89.8156,DL,...,Phones,Item B,3961.92,9,0.28,-320.77,10,2021,-0.080963,Very High